spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/testDB?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: postgres
    password: Admin123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
